name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag factory39/k8s-builder-deployer:$(git rev-parse --short HEAD)
    - name: Docker Push Sha
      run: docker push factory39/k8s-builder-deployer:$(git rev-parse --short HEAD)
    - name: Docker Tag Latest
      run: docker tag factory39/k8s-builder-deployer:$(git rev-parse --short HEAD) factory39/k8s-builder-deployer:latest
    - name: Docker Push Latest
      run: docker push factory39/k8s-builder-deployer:latest
    
